### ISSUE TITLE
Easy Install Doesn't Install

### ISSUE THREAD

**Issue by KD2VZJ** [adafruit/Adafruit-PiTFT-3.5-Plus-PCB#2]
With the recent removal of the default "pi" user account, the install fails while trying to execute the console install command, specifically the following command for my set-up:

sudo python3 adafruit-pitft.py --display=35r --rotation=90 --install-type=console

 The error message that is returned is:

PITFT Exiting due to error: /home/pi must be an existing directory (use -u /home/pi/foo to specify)

**Comment by ladyada** [comment]
please keep issues to the firmware/software repo - this isnt reltaed to hardware
